# general settings
seed: 4 # run seed
n_ant: 12 # number of received signals
detector_type: 'rec_deepsic' # ['rec_deepsic','hyper_deepsic']
training_type: 'Online' # ['Joint','Online']

# train settings
train_block_length: 100 # coherence block time, total size of pilot + data. values: int.

# test settings
test_block_length: 21000 # coherence block time, total size of pilot + data. values: int.
test_pilots_length: 1000 # pilot bits
test_blocks_num: 100 # number of validation frames. values: int.