# general
seed: 5 # run seed

# MIMO protocol
block_length: 15000 # coherence block time, total size of pilot + data. values: int.
pilots_length: 500 # pilot bits
blocks_num: 30 # number of validation frames. values: int.
n_user: 3 # number of transmitting devices
n_ant: 12 # number of received signals

# training hyperparameters
detector_type: 'online_hyper_deepsic' # ['seq_deepsic','rec_deepsic','online_hyper_deepsic']
hidden_base_size: 24 # size of the hidden layer in DeepSIC