# general settings
seed: 3 # run seed
n_ant: 12 # number of received signals
detector_type: 'rec_deepsic' # ['seq_deepsic','rec_deepsic','hyper_deepsic']
training_type: 'Joint' # ['Joint','Online']

# train settings
train_block_length: 1000 # coherence block time, total size of pilot + data. values: int.
train_blocks_num: 1000 # number of validation frames. values: int.

# test settings
test_block_length: 15000 # coherence block time, total size of pilot + data. values: int.
test_pilots_length: 5000 # pilot bits
test_blocks_num: 100 # number of validation frames. values: int.